version: '3.8'
services:

  db:
    image: mariadb
    restart: always
    env_file: .env
    environment:
      MARIADB_USER: $MARIADB_USER
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: $MARIADB_DATABASE
    ports:
      - $MARIADB_LOCAL_PORT:$MARIADB_DOCKER_PORT
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    env_file: .env
    environment:
      SERVER_PORT: $SPRING_DOCKER_PORT
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:$MARIADB_DOCKER_PORT/$MARIADB_DATABASE
      SPRING_DATASOURCE_USERNAME: $MARIADB_USER
      SPRING_DATASOURCE_PASSWORD: $MARIADB_ROOT_PASSWORD
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: